#!/bin/bash
set -u -o pipefail

SCRIPT_PATH=$(dirname $0)
TESTS_DIR="$SCRIPT_PATH/tests"
SRC_DIR="$SCRIPT_PATH/src"
BUILD_DIR="$SCRIPT_PATH/build"
PYTHON=$(which python)

rm $TESTS_DIR/*.s
rm $BUILD_DIR/*

for FILE in $TESTS_DIR/*.py
do
	NOEXT=${FILE%.py}
    NOEXT_BASE=$(basename $NOEXT)
    EXE=$BUILD_DIR/$(basename $NOEXT)
	
	# Compile each file and run through gcc
	$PYTHON $SRC_DIR/compile.py $FILE

	# Note: WARNING MESSAGES ARE OFF
	gcc -m32 -lm -w "$NOEXT.s" $SRC_DIR/*.c -lm -o $EXE
	if [[ $? != 0 ]]; then
		echo "$NOEXT_BASE gcc compile failed!"
		break
	fi

	#Compare the output of the compiled filed to the
	#output of the python interpreter
    if [[ -e "$NOEXT.in" ]]; then
        $EXE > $EXE.a.out < "$NOEXT.in" 
        $PYTHON $FILE > $EXE.py.out < "$NOEXT.in"
    else
        $EXE > $EXE.a.out
        $PYTHON $FILE > $EXE.py.out
    fi
	diff $EXE.a.out $EXE.py.out
	if [ $? != 0 ]; then
		echo "$NOEXT_BASE failed!"
		break
	fi
	echo "$NOEXT_BASE passed!"
done
